spring.config.activate.on-profile=local
spring.datasource.url=${LOCAL_DB_URL:jdbc:h2:file:./data/moiltae;MODE=MySQL;AUTO_SERVER=TRUE}
spring.datasource.username=${LOCAL_DB_USERNAME:sa}
spring.datasource.password=${LOCAL_DB_PASSWORD:}
spring.datasource.driver-class-name=org.h2.Driver
